### ISSUE TITLE
Preferred work group size multiple (kernel) not working with latest Nvidia compiler

### ISSUE THREAD

**Issue by villekf** [Oblomov/clinfo#79] opened 2022-05-01 09:52 UTC
Linux drivers for Nvidia GPUs support Clang/NVVM 7 starting at least from 510.47.03 (Windows from 511.23). The new compiler can be enabled with `NVCL_USE_NVVM70_COMPILER=1` (see for example https://www.reddit.com/r/OpenCL/comments/s41lxf/nvidia_is_updating_its_opencl_compiler_from_clang/ or https://docs.nvidia.com/datacenter/tesla/tesla-release-notes-510-47-03/index.html). However, after setting this the Preferred work group size multiple (kernel) fails with the below message

```
=== CL_PROGRAM_BUILD_LOG ===
  Preferred work group size multiple (kernel)     <getWGsizes:1583: create kernel : error -45>
```

When using the default compiler, everything works fine. 

This was tested with the latest master.

**Comment by Oblomov** [comment] 2022-05-01 10:11
Hello,

thanks for the report, but I'm afraid this is an issue with the platform rather than with `clinfo`. Error -45 means that the compiler is failing to correctly build the device-side code. The build log should have been output to stderr, if you can paste here we can double-check if there's some issue in the definitions, but I'm pretty sure the issue is in the platform itself.

**Comment by villekf** [comment] 2022-05-09 08:36
The only output from stderr seems to be `=== CL_PROGRAM_BUILD_LOG ===`.

**Comment by Oblomov** [comment] 2022-05-09 08:42
This is very strange. it means that the device compiler is also producing an empty build log. I think this confirms that the issue is in the device compiler itself. I would recommend reporting this issue to the platform developers, pointing out that there are at least two issues: (1) the compiler fails to build a very simple program and (2) it fails to produce a proper error log on failure.

Since this is actually an issue in the OpenCL plaform and there's nothing we can do in clinfo to fix this (at this at the moment), I'm closing the issue now.

**Closed by Oblomov** 2022-05-09 08:42 UTC

**Comment by rdellison** [comment] 2022-05-10 17:42
I see this also on a yocto system using the Vivante OpenCL built into i.mx8qm chip

Number of platforms                               1
  Platform Name                                   Vivante OpenCL Platform
  Platform Vendor                                 Vivante Corporation
  Platform Version                                OpenCL 1.2 V6.4.3.p1.305572
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             viv

  Platform Name                                   Vivante OpenCL Platform
Number of devices                                 1
  Device Name                                     Vivante OpenCL Device GC7000XSVX.6009.0000
  Device Vendor                                   Vivante Corporation
  Device Vendor ID                                0x564956
  Device Version                                  OpenCL 1.2 
  Driver Version                                  OpenCL 1.2 V6.4.3.p1.305572
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               2
  Max clock frequency                             996MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     (n/a)
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             1024
=== CL_PROGRAM_BUILD_LOG ===
(6:0) : error : syntax error at 'kernel'
  Preferred work group size multiple              <getWGsizes:1200: create kernel : error -45>

**Comment by Oblomov** [comment] 2022-05-10 18:29
This is a different issue (and there is an actual log in this case). Can you please open a separate issue and paste the full clinfo log?
