### ISSUE TITLE
clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...) printing random bytes

### ISSUE THREAD

**Issue by Cat22** [Oblomov/clinfo#51] opened 2020-07-05 16:17 UTC
clinfo version 2.2.18.04.06 from openSuse distribution (I also comoiled  and tested the current git version)
Running 2 NVIDIA gpu's: RTX2060 and a GTX 1660 ti  under openSuse Leap 15.2
clinfo prints random data  for clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)
Both devices seem to work ok running milkyway@home
See attached file
[clinfo.txt](https://github.com/Oblomov/clinfo/files/4875216/clinfo.txt)

**Comment by Oblomov** [comment] 2020-07-05 19:26
https://github.com/Oblomov/clinfo/issues/51

**Comment by Oblomov** [comment] 2020-07-05 19:27
Thanks for the report. I'm afraid I'm unable to reproduce locally due to the very different setup, but I believe I have found the issue and pushed a fix. I would appreciated if you could pull the latest and see if it's fixed (in either case, if the output changed, can you please show me the new output for that section?)

**Comment by Cat22** [comment] 2020-07-06 05:56
I tried the latest git version as you requested and it seems to work ok - see attachment.
One question: why does it show 'NULL platform behavior' ? The listing for that shows no devices found for everything under that but when checking above it finds both GPU devices and 2 platforms.
[clinfo.txt](https://github.com/Oblomov/clinfo/files/4876982/clinfo.txt)

**Comment by Oblomov** [comment] 2020-07-06 13:32
The behavior of those API calls when the platform is NULL is implementation-dependent (i.e. depends on the specific `libOpenCL`). Different OpenCL libraries behave in different ways: they may delegate to a specific ICD, or the first one available, or any other behavior. If you change `libOpenCL`, while maintaining the same setup (i.e. the same available ICDs) you may see different behavior.

I'm closing this issue as fixed in the mean time, thanks for the report.

**Closed by Oblomov** 2020-07-06 13:32 UTC
