### ISSUE TITLE
Links to both Windows Binaries are broken

### ISSUE THREAD

**Issue by samjfuller** [Oblomov/clinfo#88] opened 2023-08-08 01:13 UTC
When clicking the link to either set of binaries, it comes up with a blank page stating "{"message":"Artifact not found or access denied."}"

I'm guessing this isn't supposed to happen?

**Comment by samjfuller** [comment] 2023-08-08 01:16
Looks like the .exe is available here: https://github.com/ahoylabs/clinfo/releases/tag/master-d2baa06

**Comment by engineer1109** [comment] 2024-04-27 14:28
My Windows Build. Same code with cmake.

Download:
https://github.com/engineer1109/clinfo/releases/tag/v1.0

**Comment by SatjaSivcev** [comment] 2024-05-09 09:17
Voting to fix this

**Comment by Oblomov** [comment] 2024-06-06 14:25
This is a duplicate of #45

**Closed by Oblomov** 2024-06-06 14:25 UTC
