### ISSUE TITLE
windows release hangs indefinitely with Intel Iris XE OpenCL3 GPU

### ISSUE THREAD

**Issue by sn10106** [Oblomov/clinfo#67] opened 2021-06-05 04:02 UTC
Hi there,

I tried running clinfo win64 release version and it hangs indefinitely in the command prompt with no output?

GPU: Intel(R) Iris(R) Xe Graphics 
GPU Driver version: 27.20.100.9316 

I've updated registries to map HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors to the Intel_OpenCL_ICD64.dll 

Using other tools such as GPU-Z or GPU Caps both show the GPU details correctly with OpenCL version and info.

Any ideas why clinfo would hang?

Cheers

**Comment by Oblomov** [comment] 2021-06-05 14:23
No idea. Can you try running inside a debugger and see where the hang happens?

**Comment by bouachalazhar** [comment] 2023-03-30 08:23
> Hi there,
> 
> I tried running clinfo win64 release version and it hangs indefinitely in the command prompt with no output?
> 
> GPU: Intel(R) Iris(R) Xe Graphics GPU Driver version: 27.20.100.9316
> 
> I've updated registries to map HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors to the Intel_OpenCL_ICD64.dll
> 
> Using other tools such as GPU-Z or GPU Caps both show the GPU details correctly with OpenCL version and info.
> 
> Any ideas why clinfo would hang?
> 
> Cheers

Hi, I can't run clinfo in cli, I have the same chip.

**Comment by Oblomov** [comment] 2023-03-30 10:41
Without any debugging information on where the hanging happens there isn't anything I can do to fix the issue.

**Comment by bouachalazhar** [comment] 2023-03-30 11:05
> Without any debugging information on where the hanging happens there isn't anything I can do to fix the issue.

In my terminal, I have `OpenCL™ and OpenGL® Compatibility Pack` from Microsoft store.
```
C:\Users\Lazhar Bouacha>clinfo
'clinfo' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by Oblomov** [comment] 2023-03-30 13:17
That's an unrelated problem. I have no idea what the OpenCL and OpenGL Compatibiliy Pack installs and if clinfo is part of it. Please discuss that with Microsoft.

**Comment by Oblomov** [comment] 2024-06-06 14:25
I'm closing this issue. Feel free to reopen with the necessary information if the issue is still present and the fault happens in `clinfo` rather than the driver.

**Closed by Oblomov** 2024-06-06 14:25 UTC
